version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '80:80'
      - '443:443'      
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - .:/home
      - $HOME/.cache/huggingface:/root/.cache/huggingface
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'

volumes:
  mysql_data: