"""Add pdf-related columns for Message table

Revision ID: 068ed2c7468d
Revises: 548b06e68306
Create Date: 2023-10-29 12:19:08.668358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "068ed2c7468d"
down_revision = "548b06e68306"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message", sa.Column("pdf_path", sa.String(length=255), nullable=True)
    )
    op.add_column("message", sa.Column("is_pdf", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "pdf_path")
    op.drop_column("message", "is_pdf")
    # ### end Alembic commands ###
