"""add max_length to message table

Revision ID: 4cc02da8d099
Revises: b0a1bc00c080
Create Date: 2023-09-05 12:45:54.861555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4cc02da8d099"
down_revision = "b0a1bc00c080"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("max_length", sa.Integer(), nullable=False))
    op.add_column("message", sa.Column("temperature", sa.Float(), nullable=False))
    op.add_column("message", sa.Column("top_k", sa.Integer(), nullable=False))
    op.add_column("message", sa.Column("top_p", sa.Float(), nullable=False))
    op.add_column(
        "message", sa.Column("repetition_penalty", sa.Float(), nullable=False)
    )
    op.add_column(
        "message", sa.Column("no_repeat_ngram_size", sa.Integer(), nullable=False)
    )
    op.add_column(
        "training_parameter", sa.Column("max_length", sa.Integer(), nullable=False)
    )
    op.drop_column("training_parameter", "run_on_gpu")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_parameter",
        sa.Column(
            "run_on_gpu",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("training_parameter", "max_length")
    op.drop_column("message", "no_repeat_ngram_size")
    op.drop_column("message", "repetition_penalty")
    op.drop_column("message", "top_p")
    op.drop_column("message", "top_k")
    op.drop_column("message", "temperature")
    op.drop_column("message", "max_length")
    # ### end Alembic commands ###
