"""Add train loss and runtime property for training parameter

Revision ID: 543bef763e4d
Revises: 4cc02da8d099
Create Date: 2023-10-25 01:08:17.780460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543bef763e4d'
down_revision = '4cc02da8d099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_parameter', sa.Column('train_runtime', sa.Float(), nullable=False))
    op.add_column('training_parameter', sa.Column('train_loss', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_parameter', 'train_loss')
    op.drop_column('training_parameter', 'train_runtime')
    # ### end Alembic commands ###
