"""Add train loss and task property for training parameter

Revision ID: 682a279465bb
Revises: 543bef763e4d
Create Date: 2023-10-25 01:28:29.349291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '682a279465bb'
down_revision = '543bef763e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_parameter', sa.Column('task', sa.String(length=255), nullable=False))
    op.drop_column('training_parameter', 'train_runtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_parameter', sa.Column('train_runtime', mysql.FLOAT(), nullable=False))
    op.drop_column('training_parameter', 'task')
    # ### end Alembic commands ###
