"""empty message

Revision ID: 83141d1d50ff
Revises: 168234a996ab
Create Date: 2023-08-28 16:08:23.215022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83141d1d50ff'
down_revision = '168234a996ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetuning_model', sa.Column('task', sa.Integer(), nullable=False, comment='모델의 목적:: 0 QA 1 Classification 2 Generate'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finetuning_model', 'task')
    # ### end Alembic commands ###
