"""Add new tables

Revision ID: e4e34deaa93a
Revises: 3a24a085d59b
Create Date: 2023-08-23 18:14:06.992548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e34deaa93a'
down_revision = '3a24a085d59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretrained_model',
    sa.Column('pm_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False, comment='해당 모델의 베이스모델 명'),
    sa.Column('dl_url', sa.String(length=255), nullable=False),
    sa.Column('dl_mirror', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.String(length=1000), nullable=True, comment='훈련을 위한 파라미터와 기본값. json 형식의 긴 텍스트로 저장. 예: {"batch_size": 32, "learning_rate": 1e2222, ...}'),
    sa.PrimaryKeyConstraint('pm_no')
    )
    op.create_table('finetuning_model',
    sa.Column('fm_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('pm_no', sa.Integer(), nullable=False),
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('fm_description', sa.String(length=255), nullable=True, comment='해당 파인튜닝 모델에 대한 설명(*디자인에 반영안됨, 우선순위 낮음)'),
    sa.ForeignKeyConstraint(['pm_no'], ['pretrained_model.pm_no'], ),
    sa.ForeignKeyConstraint(['user_no'], ['users.user_no'], ),
    sa.PrimaryKeyConstraint('fm_no')
    )
    op.create_table('training_session',
    sa.Column('session_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('fm_no', sa.Integer(), nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('parent_session_no', sa.Integer(), nullable=False, comment='부모 모델의 세션번호'),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('ft_model_name', sa.String(length=50), nullable=False, comment='해당 세션으로 파인튜닝된 모델의 이름'),
    sa.ForeignKeyConstraint(['fm_no'], ['finetuning_model.fm_no'], ),
    sa.PrimaryKeyConstraint('session_no', 'fm_no')
    )
    op.create_table('training_parameter',
    sa.Column('parameter_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('session_no', sa.Integer(), nullable=False),
    sa.Column('fm_no', sa.Integer(), nullable=False, comment='AUTO_INCREMENT'),
    sa.Column('parameters', sa.String(length=1000), nullable=False, comment='json 형식의 긴 텍스트로 저장. 예: {"batch_size": 32, "learning_rate": 1e2222, ...}'),
    sa.Column('dataset', sa.String(length=255), nullable=False, comment='훈련에 쓰인 dataset file path'),
    sa.ForeignKeyConstraint(['fm_no'], ['finetuning_model.fm_no'], ),
    sa.ForeignKeyConstraint(['session_no'], ['training_session.session_no'], ),
    sa.PrimaryKeyConstraint('parameter_no', 'fm_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_parameter')
    op.drop_table('training_session')
    op.drop_table('finetuning_model')
    op.drop_table('pretrained_model')
    # ### end Alembic commands ###
