"""add message and test table

Revision ID: e96512344a4c
Revises: 3839baa07e37
Create Date: 2023-08-31 22:32:31.998109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96512344a4c'
down_revision = '3839baa07e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO INCRAMENT'),
    sa.Column('session_no', sa.Integer(), nullable=False),
    sa.Column('fm_no', sa.Integer(), nullable=False, comment='AUTO INCRAMENT'),
    sa.ForeignKeyConstraint(['fm_no'], ['finetuning_model.fm_no'], ),
    sa.ForeignKeyConstraint(['session_no'], ['training_session.session_no'], ),
    sa.PrimaryKeyConstraint('test_no')
    )
    op.create_table('message',
    sa.Column('msg_no', sa.Integer(), autoincrement=True, nullable=False, comment='AUTO INCRAMENT'),
    sa.Column('msg', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_user', sa.Integer(), nullable=False, comment='1 is user, otherwise model'),
    sa.Column('test_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_no'], ['test.test_no'], ),
    sa.PrimaryKeyConstraint('msg_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('test')
    # ### end Alembic commands ###
