"""Add new tables and modify user

Revision ID: ea146646c535
Revises: 005ce6e94401
Create Date: 2023-08-23 16:18:59.407755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea146646c535"
down_revision = "005ce6e94401"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_no", sa.Integer(), autoincrement=True, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_no")
    # ### end Alembic commands ###
