"""fix_error_modify_columns

Revision ID: eea5902b0e33
Revises: f0f5f640ba3f
Create Date: 2023-08-27 03:10:06.422277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eea5902b0e33'
down_revision = 'f0f5f640ba3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_parameter', 'fm_no',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='AUTO_INCREMENT',
               existing_nullable=False)
    op.alter_column('training_parameter', 'save_total_limits',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('training_session', sa.Column('ts_model_name', sa.String(length=50), nullable=False, comment='해당 세션으로 파인튜닝된 모델의 이름-epoch, loss율로 표시'))
    op.alter_column('training_session', 'fm_no',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='AUTO_INCREMENT',
               existing_nullable=False)
    op.alter_column('training_session', 'start_time',
               existing_type=mysql.DATETIME(),
               comment='YYYY-MM-DD HH:MM:SS',
               existing_nullable=False)
    op.alter_column('training_session', 'end_time',
               existing_type=mysql.DATETIME(),
               comment='YYYY-MM-DD HH:MM:SS',
               existing_nullable=False)
    op.drop_column('training_session', 'ft_model_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('ft_model_name', mysql.VARCHAR(length=50), nullable=False, comment='해당 세션으로 파인튜닝된 모델의 이름'))
    op.alter_column('training_session', 'end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='YYYY-MM-DD HH:MM:SS',
               existing_nullable=False)
    op.alter_column('training_session', 'start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='YYYY-MM-DD HH:MM:SS',
               existing_nullable=False)
    op.alter_column('training_session', 'fm_no',
               existing_type=mysql.INTEGER(display_width=11),
               comment='AUTO_INCREMENT',
               existing_nullable=False)
    op.drop_column('training_session', 'ts_model_name')
    op.alter_column('training_parameter', 'save_total_limits',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('training_parameter', 'fm_no',
               existing_type=mysql.INTEGER(display_width=11),
               comment='AUTO_INCREMENT',
               existing_nullable=False)
    # ### end Alembic commands ###
