"""empty message

Revision ID: faef5ed72a73
Revises: 83141d1d50ff
Create Date: 2023-08-29 16:44:31.950818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faef5ed72a73'
down_revision = '83141d1d50ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('uuid', sa.String(length=50), nullable=False, comment='저장 폴더명에 사용되는 uuid'))
    op.alter_column('training_session', 'ts_model_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='해당 세션으로 파인튜닝된 모델의 이름-기본값: epoch, loss로 표시',
               existing_comment='해당 세션으로 파인튜닝된 모델의 이름-epoch, loss율로 표시',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_session', 'ts_model_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='해당 세션으로 파인튜닝된 모델의 이름-epoch, loss율로 표시',
               existing_comment='해당 세션으로 파인튜닝된 모델의 이름-기본값: epoch, loss로 표시',
               existing_nullable=False)
    op.drop_column('training_session', 'uuid')
    # ### end Alembic commands ###
