name: Deploy dev
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pull origin dev
      run: |
        cd backend && git pull origin dev
    - name: Deploy dev
      run: |
        sh deploy.sh