name: Deploy dev
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: [self-hosted, label-elmo]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: dev
    - run: |
        git fetch && git pull origin dev
    - name: Deploy dev
      run: |
        sh ~/deploy.sh